name: data upload to azure

env:
  ticker: WIPRO.NS
  start: 366
  end: 1

on:
  # schedule:
  #   - cron: "1 1 * * 1"

  # push:
    # branches: [data-upload-automation, main] # Can't trigger on push because github actions pushes changes
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #   - .github/workflows/data_pipeline.yml
  #   - jobs/data_download.py
  #   - jobs/data_upload.yml
  #   - cli/setup.sh


jobs:
  datawork:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT }}
        repository: 'coderkol95/MLOps_stock_prediction'
    - name: setup python 3.9
      uses: actions/setup-python@v4
      with: 
        python-version: "3.9"
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: download ticker data and update yml file
      run: python data_download.py --ticker $ticker --start $start --end $end
      id: data
      working-directory: jobs
    - name: edit yaml files
      run: python update_yamls.py
      working-directory: jobs
    - name: push files to github
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Ticker data for $ticker downloaded and YAML file updated." || exit 0
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: setup
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: upload to azure
      run: az ml data create -f jobs/data_upload.yml